import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.js rendering methods</h1>

        <p className={styles.description}>
          You can edit the project on{" "}
          <code className={styles.code}>
            <a
              className={styles.link}
              href="https://codesandbox.io/s/nextjs-rendering-udevzh"
            >
              CodeSandbox
            </a>
          </code>
        </p>

        <div className={styles.grid}>
          <Link href="/server-side-rendering">
            <a className={styles.card}>
              <h2>Server-Side Rendering &rarr;</h2>
              <p>Server-Side Rendered page</p>
            </a>
          </Link>
          <Link href="/static-site-generation">
            <a className={styles.card}>
              <h2>Static Site Generation &rarr;</h2>
              <p>Static Site Generated page</p>
            </a>
          </Link>
          <Link href="/client-side-rendering">
            <a className={styles.card}>
              <h2>Client-Side Rendering &rarr;</h2>
              <p>Client-Side Rendered page</p>
            </a>
          </Link>
          <Link href="/incremental-static-regeneration">
            <a className={styles.card}>
              <h2>Incremental Static Regeneration &rarr;</h2>
              <p>Incremental Static Regenerated page</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
